apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: app
spec:
  replicas: 333
  selector:
    matchLabels:
        app: app
  template:
    metadata:
      labels:
          app: app
    spec:
      containers:
        - name: app
          image: iskmm/app-helm:{{ .Values.env.APP_VERSION }}
          ports:
            - containerPort: 3000
          env:
            - name: NAME
              value: 'iskmm'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialdelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
